{
  "type": "record",
  "namespace": "org.example",
  "name": "CustomerV2",
  "doc": "Avro schema for a Customer",
  "fields": [
    {
      "name": "first_name",
      "type": "string",
      "doc": "Customer's first name"
    },
    {
      "name": "last_name",
      "type": "string",
      "doc": "Customer's last name"
    },
    {
      "name": "age",
      "type": "int",
      "doc": "Customer's age in years"
    },
    {
      "name": "height",
      "type": "float",
      "doc": "Customer's height in centimeters"
    },
    {
      "name": "weight",
      "type": "float",
      "doc": "Customer's weight in kilograms"
    },
    {
      "name": "phone_number",
      "type": [
        "null",
        "string"
      ],
      "default": null,
      "doc": "optional phone number"
    },
    {
      "name": "email",
      "type": "string",
      "default": "missing@example.com",
      "doc": "email address"
    }
  ]
}
